from rdf import RDFSerializable
from uri import NamespaceResolver

class FoodGroup(RDFSerializable):
    '''
    The FoodGroup class describes a food group outlined by the USDA
    for classifying foods.
    '''
    def __init__(self):
        RDFSerializable.__init__(self)
        self.id = ""
        self.label = ""
        self.addType(NamespaceResolver.getURI("owl")+"Class")
        
    def begin(self,file):
        file.write("<nndsr:FoodGroup rdf:about=\""+self.getID()+"\">")

    def serialize(self, file):
        RDFSerializable.serialize(self, file)
    
    def end(self,file):
        file.write("</nndsr:FoodGroup>")

    def getID(self):
        return NamespaceResolver.getURI("nndsr")+"food-groups/"+self.id

class FoodGroupParser:
    def __init__(self):
        self.results = {}
    
    def parseFile(self, file):
        self.results = {}
        file = open(file,"r")
        try:
            for entry in file:
                entry = entry.strip()
                cols = entry.split("^")
                group = FoodGroup()
                group.id = cols[0].strip("~")
                group.label = cols[1].strip("~")
                group.comment = "Autogenerated food group '"+group.label+"' from the USDA National Nutrient Database for Standard Reference"
                self.results[group.id] = group
        except :
            return None
        return self.results
